/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.Controlador;

/**
 *
 * @author Wim
 */
public class FinDelDia extends javax.swing.JFrame {

    /**
     * Creates new form FinDelDia
     */
    private Controlador Controlador;

    public FinDelDia(Controlador Controlador) {
        this.Controlador = Controlador;
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        VentasLabel = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        PlatoLabel = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        CamareroLabel = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        FinMesaTable = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        MenosVendidoLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        AliLabel = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(388, 415));
        setPreferredSize(new java.awt.Dimension(397, 390));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 22)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Fin del dia");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(138, 11, 120, 28);

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Total de ventas:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 74, 100, 16);

        VentasLabel.setFont(new java.awt.Font("Trebuchet MS", 0, 15)); // NOI18N
        VentasLabel.setText("jLabel3");
        getContentPane().add(VentasLabel);
        VentasLabel.setBounds(10, 90, 60, 20);

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Plato mas vendido:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 240, 120, 16);

        PlatoLabel.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        PlatoLabel.setText("jLabel5");
        getContentPane().add(PlatoLabel);
        PlatoLabel.setBounds(10, 260, 330, 18);

        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("Empleado del mes:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(10, 142, 120, 16);

        CamareroLabel.setFont(new java.awt.Font("Trebuchet MS", 0, 15)); // NOI18N
        CamareroLabel.setText("jLabel7");
        getContentPane().add(CamareroLabel);
        CamareroLabel.setBounds(10, 160, 60, 19);

        FinMesaTable.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N
        FinMesaTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mesa", "Ventas"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        FinMesaTable.getTableHeader().setResizingAllowed(false);
        FinMesaTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(FinMesaTable);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(150, 60, 210, 140);

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("Plato menos vendido:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 200, 130, 16);

        MenosVendidoLabel.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        MenosVendidoLabel.setText("jLabel8");
        getContentPane().add(MenosVendidoLabel);
        MenosVendidoLabel.setBounds(10, 220, 340, 20);

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Alimentos agotados:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 280, 120, 16);

        AliLabel.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        AliLabel.setText("jLabel7");
        getContentPane().add(AliLabel);
        AliLabel.setBounds(10, 300, 340, 18);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/depositphotos_23928845-stock-photo-green-pastel-background-design.jpg"))); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(-6, -6, 400, 390);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FinDelDia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FinDelDia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FinDelDia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FinDelDia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Controlador c = null;
                new FinDelDia(c).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel AliLabel;
    public javax.swing.JLabel CamareroLabel;
    public javax.swing.JTable FinMesaTable;
    public javax.swing.JLabel MenosVendidoLabel;
    public javax.swing.JLabel PlatoLabel;
    public javax.swing.JLabel VentasLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
